# The URL the site will be built for
base_url = "https://smooth-zola.netlify.app/"

title = "Your website title"
description = "Your website description!"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    { name = "technologies" },
    { name = "year", feed = true }
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "base16-ocean-dark"
external_links_target_blank = true
smart_punctuation = true

[extra]
smooth_main_menu_links = [
    { name = "home", url = "/" },
    { name = "about", url = "/about/" },
    { name = "blog", url = "/blog/" },
    { name = "portfolio", url = "/portfolio/" },
    { name = "changelog", url="/changelog/" }
]
smooth_footer_description = """
# Hello!
My name is...
"""
smooth_footer_menu = true
smooth_footer_links = [
    { social = "GitHub", url = "https://github.com" },
    { social = "Twitter", url = "https://twitter.com" },
    { social = "YouTube", url = "https://youtube.com" },
]