name = "smooth"
description = "a simple portfolio theme"
license = "MIT"
homepage = "https://github.com/rhyses-pieces/smooth-theme/"
min_version = "0.16.1"
demo = "https://smooth-zola.netlify.app/"

taxonomies = [
    { name = "technologies" },
    { name = "year", feed = true }
]

[extra]
smooth_main_menu_links = []
smooth_footer_description = """
"""
smooth_footer_menu = false
smooth_footer_links = []

[author]
name = "Rhys Kim"
homepage = ""
